### ISSUE TITLE
Support for IntellIJ IDEA 2020.1

### ISSUE THREAD

**Issue by zsolt-donca** [vbmacher/intellij-cucumber-scala#50]
The current version of the plugin doesn't seem to support the recently released IDEA version 2020.1. I installed the plugin through the built-in Plugins section, and the version appears `2018.2.0 Feb 03, 2020`.

The issue is that the analysis of a .feature file doesn't seem to every finish (the little eye icon in the top-right corner doesn't disappear), and the highlighting of the steps in the .feature files doesn't work properly either.

I get the below in the IDE Internal Errors view:
```
java.lang.NoClassDefFoundError: org/jetbrains/plugins/scala/lang/psi/stubs/util/ScalaStubsUtil$
	at com.github.danielwegener.intellij.cucumber.scala.CucumberScalaExtension.$anonfun$loadStepsFor$1(CucumberScalaExtension.scala:66)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:244)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:244)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:241)
	at scala.collection.mutable.ArrayOps$ofRef.flatMap(ArrayOps.scala:198)
	at com.github.danielwegener.intellij.cucumber.scala.CucumberScalaExtension.loadStepsFor(CucumberScalaExtension.scala:65)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepHelper.loadStepsFor(CucumberStepHelper.java:130)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepHelper.findStepDefinitions(CucumberStepHelper.java:77)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinitions(CucumberStepReference.java:153)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinition(CucumberStepReference.java:143)
	at org.jetbrains.plugins.cucumber.psi.annotator.GherkinAnnotatorVisitor.visitStep(GherkinAnnotatorVisitor.java:73)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.acceptGherkin(GherkinStepImpl.java:99)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinPsiElementBase.accept(GherkinPsiElementBase.java:70)
	at org.jetbrains.plugins.cucumber.psi.annotator.GherkinAnnotator.annotate(GherkinAnnotator.java:16)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:129)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:110)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:346)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:280)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:306)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:309)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:277)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:52)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:427)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:402)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:171)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.plugins.scala.lang.psi.stubs.util.ScalaStubsUtil$ PluginClassLoader[com.github.danielwegener.cucumber-scala, 2018.2.0] com.intellij.ide.plugins.cl.PluginClassLoader@502f7675
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 46 more
```

**Comment by vbmacher** [comment]
Thanks for reporting, working on it now.

**Comment by vbmacher** [comment]
Released in https://github.com/vbmacher/intellij-cucumber-scala/releases/tag/2020.1
