### ISSUE TITLE
High CPU usage and lots of exceptions in idea.log

### ISSUE THREAD

**Issue by michalmela-tomtom** [vbmacher/intellij-cucumber-scala#95]
**Describe the bug**
 * CPU usage in Activity Monitor spikes up 300-600%, JIT Compiler CPU usage stays at aroun1 100%, other sub-processes seem to stay at rather low and expected CPU Usage values.
 * idea.log is riddled with occurrences of the following exception:

```
2021-02-06 18:58:59,654 [  43382]  ERROR - ht.daemon.impl.LineMarkersPass - IdeaLoggingEvent[message=During querying provider com.github.vbmacher.intellij.cucumber.scala.search.ScCucumberLineMarkerProvider@e3a9442 (class com.github.vbmacher.intellij.cucumber.scala.search.ScCucumberLineMarkerProvider), throwable=java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:627)
	at scala.None$.get(Option.scala:626)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$implicits$ScMethodCallExt.stepDefinitionInnerMethod$lzycompute(StepDefinition.scala:22)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$implicits$ScMethodCallExt.stepDefinitionInnerMethod(StepDefinition.scala:22)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$implicits$ScMethodCallExt.getName(StepDefinition.scala:33)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$implicits$ScMethodCallExt.isStepDefinition(StepDefinition.scala:63)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.isStepDefinition(StepDefinition.scala:103)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.$anonfun$fromLeafPsiElement$4(StepDefinition.scala:76)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.$anonfun$fromLeafPsiElement$4$adapted(StepDefinition.scala:74)
	at scala.Option$WithFilter.map(Option.scala:319)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.$anonfun$fromLeafPsiElement$3(StepDefinition.scala:74)
	at scala.Option.flatMap(Option.scala:283)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.$anonfun$fromLeafPsiElement$2(StepDefinition.scala:73)
	at scala.Option$WithFilter.flatMap(Option.scala:283)
	at com.github.vbmacher.intellij.cucumber.scala.psi.StepDefinition$.fromLeafPsiElement(StepDefinition.scala:70)
	at com.github.vbmacher.intellij.cucumber.scala.search.ScCucumberLineMarkerProvider.getLineMarkerInfo(ScCucumberLineMarkerProvider.scala:18)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:158)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:83)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:81)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:78)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**To Reproduce**
Have the IDE running with the Cucumber for Scala enabled.

Observed for a few days now, but I cannot pinpoint it to any specific change in my configuration.

**Expected behavior**
(observed after disabling the plugin) Total CPU Usage stays below 50%, JIT Compiler doesn't even pop up in the Activity Monitor constantly.

**Desktop (please complete the following information):**
- Intellij IDEA 2020.3.1, 2020.3.2
- plugin version 2020.3.1
- macOS Catalina 10.15.6

**Comment by vbmacher** [comment]
Hi @michalmela-tomtom , thanks for reporting. I'll have a look.

**Comment by vbmacher** [comment]
Could you please try the plugin on development branch ?

**Comment by vbmacher** [comment]
Exceptions in log have been fixed. I do not observe high CPU usage.
